spring.application.name=demo

# PostgreSQL Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finance_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Create/Validate tables strategy
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Allow Flyway/Liquibase here eventually
# spring.flyway.enabled=true
